In [27]:
import numpy as np
import torch


Training data

In [28]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [29]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [30]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Linear regression model from scratch

In [31]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.6760,  0.2721, -0.0212],
        [ 0.7878,  1.1899, -0.3436]], requires_grad=True)
tensor([-0.8997,  1.0620], requires_grad=True)


In [32]:
def model(x):
    return x @ w.t() + b

In [33]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 65.7724, 123.5198],
        [ 83.2111, 155.4725],
        [ 93.1518, 209.1180],
        [ 78.9731, 119.8700],
        [ 70.3886, 145.5985]], grad_fn=<AddBackward0>)


In [34]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Loss function

In [35]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [36]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(2427.8447, grad_fn=<DivBackward0>)


In [37]:
# Compute gradients
loss.backward()

In [38]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[ 0.6760,  0.2721, -0.0212],
        [ 0.7878,  1.1899, -0.3436]], requires_grad=True)
tensor([[ 445.3733, -659.0377, -222.4538],
        [5154.8496, 4939.2178, 3026.1045]])


In [39]:
w
w.grad

tensor([[ 445.3733, -659.0377, -222.4538],
        [5154.8496, 4939.2178, 3026.1045]])

In [40]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [41]:
# Let's verify that the loss is actually lower
loss = mse(preds, targets)
print(loss)

tensor(2427.8447, grad_fn=<DivBackward0>)


In [42]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


Train the model using gradient descent

In [43]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 65.9845, 115.1456],
        [ 83.5281, 144.4977],
        [ 93.7764, 196.2590],
        [ 78.8845, 111.3679],
        [ 70.8696, 135.1812]], grad_fn=<AddBackward0>)


In [44]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(1873.4822, grad_fn=<DivBackward0>)


In [45]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ 469.9390, -625.4019, -203.2472],
        [4291.8984, 4016.0964, 2455.6873]])
tensor([ 2.4086, 48.4903])


In [46]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [47]:
print(w)
print(b)

tensor([[ 0.6669,  0.2850, -0.0169],
        [ 0.6933,  1.1003, -0.3984]], requires_grad=True)
tensor([-0.8998,  1.0610], requires_grad=True)


In [48]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(1497.3572, grad_fn=<DivBackward0>)


Train for multiple epochs

In [49]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [50]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(277.1893, grad_fn=<DivBackward0>)


In [51]:
# Predictions
preds

tensor([[ 62.6077,  74.3434],
        [ 82.0502,  93.2898],
        [110.2968, 143.2612],
        [ 53.2059,  58.4173],
        [ 82.7232,  94.0176]], grad_fn=<AddBackward0>)

In [52]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [53]:
import torch.nn as nn

In [54]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

In [55]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

In [56]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [57]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

Dataset and DataLoader

In [58]:
from torch.utils.data import TensorDataset

In [59]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [60]:
from torch.utils.data import DataLoader

In [61]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [62]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[103.,  43.,  36.],
        [ 87., 134.,  58.],
        [ 92.,  87.,  64.],
        [101.,  44.,  37.],
        [ 91.,  87.,  65.]])
tensor([[ 20.,  38.],
        [119., 133.],
        [ 82., 100.],
        [ 21.,  38.],
        [ 80., 102.]])


nn.Linear

In [63]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.4691,  0.2411,  0.1864],
        [-0.5485,  0.4322,  0.1497]], requires_grad=True)
Parameter containing:
tensor([-0.5488,  0.0167], requires_grad=True)


In [64]:
# Generate predictions
preds = model(inputs)
preds

tensor([[-10.6303,  -4.6310],
        [-10.0985,  -2.2846],
        [  1.7482,  18.8916],
        [-31.1385, -31.8081],
        [  3.2690,  14.1381],
        [-11.3405,  -5.6117],
        [-10.1532,  -2.5671],
        [  1.4654,  18.4928],
        [-30.4283, -30.8274],
        [  3.9245,  14.8363],
        [-10.6849,  -4.9134],
        [-10.8087,  -3.2653],
        [  1.8028,  19.1740],
        [-31.7940, -32.5063],
        [  3.9791,  15.1188]], grad_fn=<AddmmBackward0>)

Loss Function

In [65]:
# Import nn.functional
import torch.nn.functional as F

In [66]:
# Define loss function
loss_fn = F.mse_loss

In [67]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(8410.6309, grad_fn=<MseLossBackward0>)


Optimizer

In [68]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

Train the model

In [69]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):

    # Repeat for given number of epochs
    for epoch in range(num_epochs):

        # Train with batches of data
        for xb,yb in train_dl:

            # 1. Generate predictions
            pred = model(xb)

            # 2. Calculate loss
            loss = loss_fn(pred, yb)

            # 3. Compute gradients
            loss.backward()

            # 4. Update parameters using gradients
            opt.step()

            # 5. Reset the gradients to zero
            opt.zero_grad()

        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [70]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 59.7161
Epoch [20/100], Loss: 36.4954
Epoch [30/100], Loss: 33.6354
Epoch [40/100], Loss: 25.4529
Epoch [50/100], Loss: 21.5890
Epoch [60/100], Loss: 22.9316
Epoch [70/100], Loss: 14.9123
Epoch [80/100], Loss: 15.0541
Epoch [90/100], Loss: 9.7064
Epoch [100/100], Loss: 9.8589


In [71]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 57.3692,  70.6959],
        [ 81.1411,  98.0362],
        [119.2070, 137.4612],
        [ 23.9312,  39.6384],
        [ 98.4100, 113.0918],
        [ 56.1775,  69.5835],
        [ 80.8095,  97.6837],
        [119.4233, 137.8218],
        [ 25.1229,  40.7508],
        [ 99.2701, 113.8517],
        [ 57.0376,  70.3434],
        [ 79.9494,  96.9238],
        [119.5385, 137.8137],
        [ 23.0711,  38.8785],
        [ 99.6017, 114.2042]], grad_fn=<AddmmBackward0>)

In [72]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [73]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[53.7846, 67.2058]], grad_fn=<AddmmBackward0>)