In [2]:
import torch as torch
#number 
t1 = torch.tensor(4.)
t1
t1.dtype

torch.float32

In [3]:
# vector 
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [4]:
# matrix

t3 = torch.tensor([[5,6],
                   [7,8],
                   [9,10]])
t3


tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [5]:
# 3-dimensional array
t4 = torch.tensor([
    [[1,2,3],
     [4,5,6]],
     [[8,7,6],
      [14,25,54]]])
t4

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 8,  7,  6],
         [14, 25, 54]]])

In [6]:
print(t1)
print(t1.shape)

print(t2)
print(t2.shape)

print(t3)
print(t3.shape)

print(t4)
print(t4.shape)

tensor(4.)
torch.Size([])
tensor([1., 2., 3., 4.])
torch.Size([4])
tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10]])
torch.Size([3, 2])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 8,  7,  6],
         [14, 25, 54]]])
torch.Size([2, 2, 3])


In [7]:
# create tesnors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b  = torch.tensor(5., requires_grad = True)
print(x)
print(w)
print(b)



tensor(3.)
tensor(4., requires_grad=True)
tensor(5., requires_grad=True)


In [8]:
# Arithmetic 
y = w * x + b
y

#As expected, y is a tensor with the value 3 * 4 + 5 = 17. What makes PyTorch special is that we can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b. To compute the derivatives, we can call the .backward method on our result y.

tensor(17., grad_fn=<AddBackward0>)

In [9]:
# compute derivative
y.backward()

In [10]:
# display gradients
print('dy/dx:', x.grad)
print('dy/dw:',w.grad)
print('dy/db:',w.grad)

# As expected, dy/dw has the same value as x i.e. 3, and dy/db has the value 1. Note that x.grad is None, because x doesn't have requires_grad set to True.

# The "grad" in w.grad stands for gradient, which is another term for derivative, used mainly when dealing with matrices


dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(3.)


In [18]:
# create a tensor with a feixed value for every element
t6 = torch.full((3,2),42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [17]:

# connection two tensors with compatible shapes
t7 = torch.cat((t3,t6))
t7

tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [42, 42],
        [42, 42],
        [42, 42]])

In [19]:
# compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [20]:

# change the shape of a tensor
t9 = t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

In [11]:

import numpy as np
x = np.array([[1,2],[3,4]])
x


array([[1, 2],
       [3, 4]])

In [15]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [13]:
x.dtype, y.dtype


(dtype('int32'), torch.int32)

In [14]:
# convert a torch tensor to a numpy arrray
z = y.numpy()
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [22]:
import jovian 
jovian.commit()

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[jovian] Error: Failed to read the Jupyter notebook. Please re-run this cell to try again. If the issue persists, provide the "filename" argument to "jovian.commit" e.g. "jovian.commit(filename='my-notebook.ipynb')"
